/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.api.thomas;

public final class Library {
    
    public boolean someLibraryMethod() {
        return true;
    }
}
